# Site
name: "DevHome"
title: "DevHome"
description: "Ajudando outros desenvolvedores."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-3983441-4'
disqus: 'https-devhome-com-br'
#mailchimp-list: 'https://devhome.us4.list-manage.com/subscribe/post?u=646e413277ea74a2986bcad72&amp;id=f8790e2262'
include: ["_pages"]
permalink: /:title/


defaults:
  - scope:
      path: ""
    values:
      lang: pt_BR
      logo: assets/images/avatar.png
      twitter:
        username: klaiddias
        card: summary
        

# Authors
authors:
  klaid:
    name: Klaid Dias
    display_name: Klaid
    gravatar: 5baac68c85a4547a48ca59b381b09506
    email: klaiddias@gmail.com
    web: https://devhome.com.br
    twitter: https://twitter.com/klaiddias
    description: "Desenvolvedor FullStack .Net, Mobile (Cordova, React), Oracle, PostgreSQL, MySQL, CMS (Wordpress, Drupal) - Entusiasta por novas tecnologias."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

  # Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-7808387889562649"
adsense-data-ad-slot: "6318770812"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, CNAME]
